config/routes.rb
Lentu::Application.routes.draw do
  root              to: 'sessions#new'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/auth/:provider/callback', to: 'sessions#create'
  resources :password_resets
  resources :email_verifications

  match '/signup',  to: 'users#new'         # signup_path
  match '/signin',  to: 'sessions#new'      # signin_path
  match '/signout', to: 'sessions#destroy',     via: :delete  # signout_path

  match '/about',   to: 'static_pages#about',   as: :about    # about_path
  match '/contact', to: 'static_pages#contact', as: :contact  # contact_path

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
    @email_default_value = params[:email]
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    user = User.find_by_email(params[:email])
    user.send_password_reset if user
    flash[:success] = "Email sent with password reset instructions."
    redirect_to signin_path
  end

  def edit
    @user = User.find_by_password_reset_token!(params[:id])
  end

  def update
    @user = User.find_by_password_reset_token!(params[:id])
    if @user.password_reset_sent_at < 10.hours.ago
      redirect_to new_password_reset_path, alert: "Password reset has expired."
    elsif @user.update_attributes(params[:user])

      flash[:success] = "Password has been reset!"
      redirect_to root_url
    else
      render :edit
    end
  end

end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/_new.html.erb
<%= form_tag :password_resets, method: 'post' do %>
  <div class="shadow">
    <div class="arrow-up"></div>
  </div>

  <div class="input-container">
    <div class="input-image input-image-email"></div>
    <%= email_field_tag :email, @email_default_value, spellcheck: false, autofocus: true %>
    <%= label_tag :email, 'Email address', id: 'email_label' %>
  </div>
  <div class="actions">
    <%= submit_tag 'Reset my password', class: "btn btn-large btn-primary" %>
  </div>
<% end %>

app/views/password_resets/edit.html.erb
<% provide :title, 'Reset Password' %>
<h1>Reset Password</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for @user, url: password_reset_path(params[:id]) do |f| %>
      <%= render 'shared/error_messages', object: @user %>
      <div class="field">
        <%= f.label :password %>
        <%= f.password_field :password %>
      </div>
      <div class="field">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
      </div>
      <div class="actions">
        <%= f.submit "Update Password", class: "btn btn-large btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<% provide :title, 'Reset password' %>
<% provide :page_specific_javascript, 'page_specific/signin.js' %>
<% provide :page_specific_css, stylesheet_link_tag('page_specific/signin.css', :media => 'all') %>
<% @hide_header = true %>
<% @hide_footer = true %>

<div id="signin" class="signin">
  <div class="signin_box">
    <div class="center portrait">
      <%= image_tag asset_path('blank.gif'), width: 150, height: 150, class: 'gravatar signin-gravatar', title: 'Your Gravatar', alt: 'Your Gravatar' %>
    </div>
    <div class="center logo">
      <%= link_to image_tag('lentu-logo-faded-150x150.png', width: 150, height: 150, alt: 'Lentu - Crowd investing in people, ideas, innovation', title: 'Lentu - Crowd investing in people, ideas, innovation'), root_path, title: 'Lentu' %>
    </div>

    <%= render 'new' %>
  </div>
  <%= link_to 'Sign in', signin_path, id: 'signin-link', remote: true, class: 'tiny-link bevel left remembers-email-in-link' %>
  <%= link_to 'Create an account', signup_path, id: 'signup-link', class: 'tiny-link bevel bold right' %>
</div>

<script>
document.getElementById("signin").style.marginTop = Math.max(0, (document.documentElement.clientHeight - 400) / 2 - 80) + "px";
</script>

app/views/password_resets/new.js.erb
$('form').after('<%= j render 'new' %>').remove();
$('a.remembers-email-in-link').after('<%= j link_to 'Sign in', signin_path, title: 'Sign in', class: 'tiny-link bevel left remembers-email-in-link', remote: true %>').remove();
document.title = "<%= full_title('Reset password') %>";
typeof initializeScript == 'function' ? initializeScript() : null;