config/routes.rb
Lentu::Application.routes.draw do
  root              to: 'sessions#new'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/auth/:provider/callback', to: 'sessions#create'
  resources :password_resets
  resources :email_verifications

  match '/signup',  to: 'users#new'         # signup_path
  match '/signin',  to: 'sessions#new'      # signin_path
  match '/signout', to: 'sessions#destroy',     via: :delete  # signout_path

  match '/about',   to: 'static_pages#about',   as: :about    # about_path
  match '/contact', to: 'static_pages#contact', as: :contact  # contact_path

end

app/views/layouts/_flash.html.erb
<div class="alert alert-<%= key %> clickable fades-on-click">
  <span class="flash-close">x</span>
  <%= value %>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <small>
      <%= link_to "Powered by Rails", 'http://rubyonrails.org/' %>
    </small>
    <nav>
      <ul>
        <li><%= link_to "About Us", about_path %></li>
        <li><%= link_to "Contact Us", contact_path %></li>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "#{ENV['APPLICATION_NAME']}", root_path, id: "logo-link", class: 'brand logo' %>
      <nav>
        <ul class="nav pull-right">
          <% if signed_in? %>
            <li><%= link_to 'Users', users_path %></li>
            <li id='fat-menu' class='dropdown'>
              <a href="#" class='dropdown-toggle' data-toggle='dropdown'>
                Account <strong class='caret'></strong>
              </a>
              <ul class='dropdown-menu'>
                <% unless current_user.email_verified? %>
                  <li><%= link_to 'Verify Email', new_email_verification_path, id: 'verify-email-link', remote: true %></li>
                  <li class='divider'></li>
                <% end %>
                <li><%= link_to 'Profile', current_user %></li>
                <li><%= link_to 'Settings', edit_user_path(current_user) %></li>
                <li class='divider'></li>
                <li>
                  <%= link_to 'Sign out', signout_path, method: 'delete' %>
                </li>
              </ul>
            </li>
          <% else %>
            <% unless @hide_signin_link %>
              <li><%= link_to "Sign in", signin_path %></li>
            <% end %>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>
<div class="header-padding"></div>

app/views/layouts/_ie_sticky_footer_fix.html.erb
<!--[if !IE 7]>
<style type="text/css">
    #wrap {display:table;height:100%}
</style>
<![endif]-->

app/views/layouts/_javascript_loader.html.erb
<script>
(function() {
  function getScript(url,success){
    var script=document.createElement('script');
    script.src=url;
    var head=document.getElementsByTagName('head')[0], done=false;
    script.onload=script.onreadystatechange = function(){
      if ( !done && (!this.readyState || this.readyState == 'loaded' || this.readyState == 'complete') ) {
        done=true;
        success();
        script.onload = script.onreadystatechange = null;
        head.removeChild(script);
      }
    };
    head.appendChild(script);
  }

  <%# Guarantees jQuery loads first %>
  getScript('//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js',function(){
    getScript('<%= asset_path('//netdna.bootstrapcdn.com/twitter-bootstrap/2.1.1/js/bootstrap.min.js') %>', function(){});
    getScript('<%= asset_path('application.js') %>', function(){
      getScript('<%= asset_path('https://www.dwolla.com/scripts/button.min.js') %>', function(){});
      <%= defer_load_javascript_file( yield(:page_specific_javascript) ).html_safe %>
    });
  });
})();
</script>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
  <!-- <%= Rails.env %> -->
  <meta charset="utf-8">
  <title><%= full_title( yield(:title) ) %></title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag '//netdna.bootstrapcdn.com/twitter-bootstrap/2.1.1/css/bootstrap-combined.min.css', :media => "all" %>
  <%= stylesheet_link_tag 'application', :media => 'all' %>
  <%= yield(:page_specific_css) %>
  <%= render "layouts/ie_sticky_footer_fix" %>
  <%= render "layouts/shim" %>
  <%= csrf_meta_tags %>
</head>
<body id="<%= "#{controller_name}_#{action_name}" %>">

<div id="wrap">
  <%= render('layouts/header') unless @hide_header %>

  <div class="main-body container">
    <% flash.each do |key, value| %>
      <%= render partial: "layouts/flash", :locals => {key: key, value: value} %>
    <% end %>

    <%= yield %>

    <div class="loader"></div>

    <%#= debug(params) if Rails.env.development? %>
    <%#= debug(request) if Rails.env.development? %>
  </div>

  <div id="push"></div>
</div>
<%= render "layouts/footer" unless @hide_footer %>

<%= render "layouts/javascript_loader" %>
</body>
</html>